CREATE DATABASE HOTEL
USE HOTEL

CREATE TABLE ROOMTYPES(
ID INT PRIMARY KEY IDENTITY,
NAME NVARCHAR(50) NOT NULL,
CAPACITY INT NOT NULL,
DAILYPRICE MONEY)
INSERT INTO ROOMTYPES VALUES('FOR 1',1,50)
INSERT INTO ROOMTYPES VALUES('FOR 2',2,80)
INSERT INTO ROOMTYPES VALUES('VIP',2,150)

CREATE TABLE ROOMS(
ID INT PRIMARY KEY IDENTITY,
ROOMTYPEID INT REFERENCES ROOMTYPES(ID),
ROOMNO INT UNIQUE NOT NULL,
ISEMPTY BIT DEFAULT 1)

INSERT INTO ROOMS VALUES(2,258,1)
INSERT INTO ROOMS VALUES(1,147,0)
INSERT INTO ROOMS VALUES(3,369,1)


CREATE TABLE CUSTOMERS(
ID INT PRIMARY KEY IDENTITY,
NAME NVARCHAR(50) NOT NULL,
SURNAME NVARCHAR(50) NOT NULL,
BIRTHDATE DATE NOT NULL,
PHONENUMBER INT NOT NULL,
PASSPORTCODE INT NOT NULL UNIQUE,
EMAIL NVARCHAR(255) NOT NULL UNIQUE,
ROOMID INT REFERENCES ROOMS(ID))


INSERT INTO CUSTOMERS
VALUES('Fidan','Mammadova','2002-09-04','0707570708',542445120,'f623@gmail.com',1)
INSERT INTO CUSTOMERS
VALUES('Gulshen','Mirzayeva','2002-09-01','0707570707',654154,'jaja@gmail.com',2)
INSERT INTO CUSTOMERS
VALUES('Narmin','Ismayilova','2002-07-28','0707570909',64163520,'eeesul@gmail.com',3)



CREATE TABLE RESERVATIONS(
ID INT PRIMARY KEY IDENTITY,
CUSTOMERID INT REFERENCES CUSTOMERS(ID),
ROOMID INT REFERENCES ROOMS(ID),
FIRSTDAY DATE NOT NULL,
ENDDAY DATE NOT NULL,
COUNTOFDAYS INT NOT NULL)

INSERT INTO RESERVATIONS 
VALUES(1,3,'2022-05-15','2022-05-20',DATEDIFF(DAY,'2022-05-15','2022-05-20'))
INSERT INTO RESERVATIONS 
VALUES(2,1,'2022-01-20','2022-01-22',DATEDIFF(DAY,'2022-01-20','2022-01-22'))
INSERT INTO RESERVATIONS 
VALUES(3,2,'2022-04-14','2022-04-15',DATEDIFF(DAY,'2022-04-14','2022-04-15'))


CREATE TABLE PAYMENTS(
ID INT PRIMARY KEY IDENTITY,
PAYMENTTYPE NVARCHAR(50),
PAYMENT MONEY,
CUSTOMERID INT REFERENCES CUSTOMERS(ID))

INSERT INTO PAYMENTS VALUES ('BY CASH',200,1)
INSERT INTO PAYMENTS VALUES ('BY CARD',100,2)


CREATE TABLE SPENDINGS(
ID INT PRIMARY KEY IDENTITY,
NAME NVARCHAR(50) NOT NULL,
CUSTOMERID INT REFERENCES CUSTOMERS(ID),
AMOUNT MONEY)

INSERT INTO SPENDINGS VALUES ('SPA',1,150)
INSERT INTO SPENDINGS VALUES ('DINNER',2,60)
INSERT INTO SPENDINGS VALUES ('GYM',3,30)

--View
CREATE VIEW View_HOTEL
AS
SELECT CUSTOMERS.NAME+' '+SURNAME AS 'FULLNAME',ROOMTYPES.NAME,ROOMS.ROOMNO FROM CUSTOMERS
join rooms
on rooms.id=CUSTOMERS.ROOMID
join ROOMTYPES
on ROOMTYPES.id=rooms.ROOMTYPEID

select * from View_HOTEL

--procedure
create procedure getspendingamounts @abc int
as 
select CUSTOMERS.name+' '+CUSTOMERS.SURNAME AS 'FullName', SPENDINGS.AMOUNT from CUSTOMERS
join SPENDINGS
ON CUSTOMERID=CUSTOMERS.ID
WHERE @abc=CUSTOMErs.ID

exec getspendingamounts @abc=2





